[package]
name = "mathx"
version = "0.2.0"
authors = ["Paul Casanova"]
edition = "2021"

[features]
default = []
no_std = []
no_vectors = []
no_quaternions = []

[dependencies]
serde = {version = "1.0.217", optional = true}
